### ISSUE TITLE
Iconfont for use on websites

### ISSUE THREAD

**Issue by WaldemarLehner** [SpyTec/EDAssets#73]
Are there any plans to publish an icon font with all the icons from EDAssets? 

If not, is it allowed to generate said font using the vector graphics? How would I go about displaying the copyright notices? Will a listing on a "About" page with the individual creators suffice?

**Comment by SpyTec** [comment]
Icon fonts is possible for the majority of the icons. For those that utilize a license that need to be attributed, e.g. CMDR Qohen's cartoon ship vectors that would not be possible without asking them first.

We do have an icon font used for the website, which we access through a [CSS file](https://file.myfontastic.com/VZM6m4cLLEE5NpFrxpPpiZ/icons.css). I've attached files from Fontastic as well, which contains almost everything except the very newest vectors.

The vectors aren't optimized to work well with fonts however, as quite a few vectors utilize lines with width rather than filled objects. This does cause some weird artefacts where lines are not shown or crops out other objects. As such I've not thought about publishing it on EDAssets until housekeeping has been done to existing assets and guidelines setup for validating vectors.

[ed-fonts.zip](https://github.com/SpyTec/EDAssets/files/2644876/ed-fonts.zip)
